[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.14.2"
lxml = "^6.0.2"
rich = "^14.2.0"
requests = "^2.32.5"
pandas = "^2.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportMissingModuleSource = false
reportOperatorIssue = false
